apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-service
  labels:
    app: financial-api-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial-api-microservice
  template:
    metadata:
      labels:
        app: financial-api-microservice
    spec:
      containers:
      - name: management-service
        image: menoita99/management_api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: management-service
  labels:
    app: financial-api-microservice
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: financial-api-microservice
  type: NodePort