apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-service
  labels:
    app: service-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-service
  template:
    metadata:
      labels:
        app: service-service
    spec:
      containers:
      - name: service-service
        image: menoita99/service_api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-service
  labels:
    app: service-service
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: service-service
  type: NodePort
