apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: "cretificatecoinpi"
    #kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
spec:
  rules:
  - host: coinpi.ddns.net
  - http:
      paths:
      - path: /management/*
        backend:
          serviceName: management-service
          servicePort: 8080
      - path: /service/*
        backend:
          serviceName: service-service
          servicePort: 8081
      - path: /*
        backend:
          serviceName: security-service
          servicePort: 8082