apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: financial-ingress
spec:
  rules:
  - http:
      paths:
      - path: /management/*
        backend:
          serviceName: management-service
          servicePort: 8080
      - path: /service/*
        backend:
          serviceName: service-service
          servicePort: 8081
#      - path: /security-service/*
      - path: /security/*
        backend:
          serviceName: security-service
          servicePort: 8082