apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /management-service
        backend:
          serviceName: management-service
          servicePort: 8080
      - path: /security-service
        backend:
          serviceName: security-service
          servicePort: 8082
      - path: /service-service
        backend:
          serviceName: service-service
          servicePort: 8081
